# Generated by Django 5.2.8 on 2025-11-23 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagegallery',
            options={'ordering': ['id'], 'verbose_name_plural': '04. Images Galleries'},
        ),
    ]
