# Generated by Django 5.2.7 on 2025-11-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_brand_slug_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(choices=[('NONE', 'None'), ('LEHENGA', 'Lehenga'), ('SHAREE', 'Sharee'), ('GENT PANTS', 'Gent Pants'), ('BORKHA', 'Borkha'), ('BABY FASHION', 'Baby Fashion')], default='NONE', max_length=50),
        ),
    ]
