# Generated by Django 5.2.7 on 2025-11-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='checkout',
            field=models.BooleanField(default=False),
        ),
    ]
