# Generated by Django 5.2.7 on 2025-11-18 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_checkout_checkout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='checkout',
            new_name='is_ordered',
        ),
    ]
