# Generated by Django 5.2.5 on 2025-10-22 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('phone', models.CharField(max_length=15)),
                ('collage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collage.collage')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collage.department')),
            ],
        ),
    ]
