# Generated by Django 6.0.3 on 2026-03-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('roll', models.PositiveIntegerField(unique=True)),
                ('department', models.CharField(choices=[('CSE', 'Computer Science'), ('EEE', 'Electrical Engineering'), ('BBA', 'Business Administration')], max_length=50)),
                ('passed_in_year', models.DateField()),
                ('passed_out_year', models.DateField()),
            ],
            options={
                'ordering': ['roll'],
            },
        ),
    ]
