# Generated by Django 6.0.3 on 2026-03-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('roll', models.IntegerField(default=101, unique=True)),
                ('department', models.CharField(max_length=200)),
                ('pased_in_years', models.IntegerField(default=0)),
                ('pased_out_years', models.IntegerField(default=0)),
            ],
        ),
    ]
