# Generated by Django 5.2.7 on 2025-11-01 13:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('phone', models.CharField(max_length=15)),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(3.5), django.core.validators.MaxValueValidator(5.0)])),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collage.collage')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collage.department')),
            ],
        ),
    ]
