# Generated by Django 5.2.5 on 2025-10-22 06:10

import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[django.contrib.auth.validators.UnicodeUsernameValidator])),
                ('state', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[django.contrib.auth.validators.UnicodeUsernameValidator])),
                ('seat', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(120)])),
                ('fees', models.DecimalField(decimal_places=2, default=650000, max_digits=10)),
                ('collage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collages', to='collage.collage')),
            ],
        ),
    ]
