# Generated by Django 5.2.8 on 2025-12-10 00:18

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ['id'], 'verbose_name_plural': '05. Product Colors'},
        ),
        migrations.AlterModelOptions(
            name='imagegallery',
            options={'ordering': ['id'], 'verbose_name_plural': '04. Image Galleries'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id'], 'verbose_name_plural': '03. Products'},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'verbose_name_plural': '07. Product Variants'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ['id'], 'verbose_name_plural': '06. Product Sizes'},
        ),
        migrations.RenameField(
            model_name='productvariant',
            old_name='is_default',
            new_name='is_featured',
        ),
        migrations.AddField(
            model_name='color',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imagegallery',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='size',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='slider',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(default='N/A'),
        ),
    ]
