# Generated by Django 5.2.8 on 2025-11-07 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='link',
        ),
    ]
